apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
  namespace: usuarios
  labels:
    app: usuarios
data:
  AWS__Region: "us-east-1"
  AWS__AccountId: "${AWS_ACCOUNT_ID}"
  PATH_BASE: "/api/usuarios"
  ASPNETCORE_URLS: "http://+:80"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  DatabaseProvider: "PostgreSql"
