apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: users
  labels:
    app: users
data:
  AWS__Region: "us-east-1"
  AWS__AccountId: "${AWS_ACCOUNT_ID}"
  PATH_BASE: "/api/users"
  ASPNETCORE_URLS: "http://+:80"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  DatabaseProvider: "PostgreSql"
  XRay__ServiceName: "fcg-users-api"
  XRay__TracingDisabled: "false"
