apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: users
  labels:
    app: users
type: Opaque
stringData:
  ConnectionStrings__Postgres: "${DB_VAL}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
  Jwt__Key: "${JWT_KEY}"
  Jwt__ExpirationTimeHour: "${JWT_EXPIRATION_TIME_HOUR}"
  Jwt__IncreaseExpirationTimeMinutes: "${JWT_INCREASE_EXPIRATION_TIME_MINUTES}"
