apiVersion: v1
kind: Secret
metadata:
  name: usuarios-secret
  namespace: usuarios
  labels:
    app: usuarios
type: Opaque
stringData:
  ConnectionStrings__PostgreSql: "${DATABASE_POSTGRES_CONNECTION_STRING}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
  Jwt__Key: "${JWT_KEY}"
  Jwt__ExpirationTimeHour: "${JWT_EXPIRATION_TIME_HOUR}"
  Jwt__IncreaseExpirationTimeMinutes: "${JWT_INCREASE_EXPIRATION_TIME_MINUTES}"
